### ISSUE TITLE
Navigation bar - Tab selected state 

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/defense-unicorns-hugo-theme#110]
## Updates
The selected state for docs top navigation bar should follow the selected state that all of our other websites currently have.

Navigation Selected state: Use secondary color for pages selected and add underline. And keep all tab names aligned horizontally.

## Reference Examples

![Screenshot 2023-09-12 at 12 24 36 PM](https://github.com/defenseunicorns/defense-unicorns-hugo-theme/assets/92826525/fe255bfb-970b-4ad3-b63d-0b1eae326a0f)
![Screenshot 2023-09-12 at 12 29 03 PM](https://github.com/defenseunicorns/defense-unicorns-hugo-theme/assets/92826525/72a9d465-6053-41eb-8ae3-cfb5b4a72cea)
![Screenshot 2023-09-12 at 12 29 12 PM](https://github.com/defenseunicorns/defense-unicorns-hugo-theme/assets/92826525/c921dc1c-b85d-4fcd-8f45-a549e931b628)

**Comment by bdfinst** [comment]
Fixed
