### ISSUE TITLE
Change Icon for pages

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/defense-unicorns-hugo-theme#111]
## Current

![IMG_0451](https://github.com/defenseunicorns/defense-unicorns-hugo-theme/assets/92826525/dbb32bef-f3cb-4cd9-ba5e-6d9f0c8bfd44)

## Update 

Change the page icon to this: 
https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Adescription%3AFILL%400%3Bwght%40300%3BGRAD%400%3Bopsz%4024
![description_FILL0_wght300_GRAD0_opsz24](https://github.com/defenseunicorns/defense-unicorns-hugo-theme/assets/92826525/2f6884af-6740-40e4-ae5f-b2f4999d9912)

**Comment by bdfinst** [comment]
Fixed
