### ISSUE TITLE
UX Change - Font to Montserrat for improved readability. 

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/defense-unicorns-hugo-theme#126]
## Current 

Currently the docs site uses Roboto for the body text. This decision was made when we were using Google Material Design System to align with the font on other open source/mission apps. 

There are some issues with this font impacting user readability on the docs site, which is text heavy
- Font weight too heavy at 400
- Font height too short 
- dense letter spacing 

## Update

- [ ] Change docs template typface default to Montserrat - with sans sarif fall back.

The transition to Carbon has made the use of roboto no longer aligned with the design system. And with the docs site falling more under our company branding it would be best to align the body font with the new website branding as well. 

The new company website uses Montserrat for it's body text.  https://fonts.google.com/specimen/Montserrat?query=Montserrat

This typeface achieves high legibility even in small sizes.
- wider letter spacing
- Featuring a large x-height
- short descenders and wide apertures,

**Comment by bdfinst** [comment]
Teams need to update their dependencies to get the update

https://main--starlit-valkyrie-7f1dd9.netlify.app/docs/
