### ISSUE TITLE
Heading Typography Color

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/defense-unicorns-hugo-theme#36]
## Current

The headings are the same color as the body text, taking away from the contrast that helps with scanning and hierarchy. 

<img width="967" alt="Screenshot 2023-07-07 at 2 59 14 PM" src="https://github.com/defenseunicorns/defense-unicorns-hugo-theme/assets/92826525/c625c01b-ded8-4a20-8e80-a8ad0ee1364c">

## Change

Make all heading font colors text primary or the equivalent (dark and light theme)
<img width="586" alt="Screenshot 2023-07-07 at 2 51 07 PM" src="https://github.com/defenseunicorns/defense-unicorns-hugo-theme/assets/92826525/acad6bf9-53fe-4609-97f9-22eb7f84a5d5">

## Design Reference

Should look something like this:

![Dark](https://github.com/defenseunicorns/defense-unicorns-hugo-theme/assets/92826525/9bd0cc98-81d3-4860-b877-3922841dafd4)

**Comment by bdfinst** [comment]
Completed
