### ISSUE TITLE
Tip and note admonitions are currently visually identical

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/defense-unicorns-hugo-theme#73]
![image](https://github.com/defenseunicorns/defense-unicorns-hugo-theme/assets/3977569/24b6617d-16e4-4cdb-890d-3596c4a73d72)

Each admonition class should have a unique style that makes it visually distinct from other admonition classes.

**Comment by bdfinst** [comment]
Changed to "success" theme color
