### ISSUE TITLE
Currently no indicated sidebar scroll position

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/defense-unicorns-hugo-theme#75]
![image](https://github.com/defenseunicorns/defense-unicorns-hugo-theme/assets/3977569/86ca6d61-1124-42e7-87c3-99dc53eb9a55)

There is currently no indicated sidebar scroll position (see below).

![image](https://github.com/defenseunicorns/defense-unicorns-hugo-theme/assets/3977569/aedcb9ac-014b-488e-82e2-75080a27e2d1)

**Comment by bdfinst** [comment]
Fixed. This was in place but regressed.
