### ISSUE TITLE
Tooltips are currently green and do not fit the theme colors

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/defense-unicorns-hugo-theme#76]
Currently tooltips such as those on the buttons in the top right are green which is not a current theme color.

![image](https://github.com/defenseunicorns/defense-unicorns-hugo-theme/assets/3977569/333a1814-f12c-4810-91c6-8057196d52b6)

**Comment by bdfinst** [comment]
As per theme. @Madeline-UX will need to advise.

**Comment by bdfinst** [comment]
Changed to primary color
