### ISSUE TITLE
Tags included in pages have limited contrast

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/defense-unicorns-hugo-theme#77]
Tags when shown in the body of a page have limited contrast - https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html

![image](https://github.com/defenseunicorns/defense-unicorns-hugo-theme/assets/3977569/35261d07-7a82-47b2-920e-c441fddcaf51)

**Comment by bdfinst** [comment]
Fixed
