### ISSUE TITLE
Sidebar does not extend through the footer, footer causes scrolling on all pages

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/defense-unicorns-hugo-theme#79]
![image](https://github.com/defenseunicorns/defense-unicorns-hugo-theme/assets/3977569/b0b6ff5a-bd8f-4bbe-8939-96a0b4027d95)

The footer extends below the content causing a break in the sidebar that forces a scroll on every page even pages that are short enough to not need to scroll

**Comment by bdfinst** [comment]
@Madeline-UX I need your input here. What behavior do we want?
