### ISSUE TITLE
There is no edit this page button

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/defense-unicorns-hugo-theme#80]
![image](https://github.com/defenseunicorns/defense-unicorns-hugo-theme/assets/3977569/eb4fa984-cf42-493f-9032-0a1d3a28e867)

Currently Zarf has an edit this page button that allows people (esp external contributors) to edit and fix pages that contain errors.

**Comment by bdfinst** [comment]
Activated metadata by default. This is configurable.
