### ISSUE TITLE
Lighthouse scores (particularly accessibility) could be improved

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/defense-unicorns-hugo-theme#82]
The Google Lighthouse scores could be improved for the docs site (particularly accessibility).

> :warning:  NOTE: Performance is low in the below due to running from a local webserver.

Hugo:

![image](https://github.com/defenseunicorns/defense-unicorns-hugo-theme/assets/3977569/8aa5e096-4623-4ee8-9cc6-2c39cfc8f370)

Current Zarf Docs:
![image](https://github.com/defenseunicorns/defense-unicorns-hugo-theme/assets/3977569/9ac3f17c-2fd2-4fe4-9e9f-ed65a4d06673)

**Comment by bdfinst** [comment]
![Screenshot 2023-08-11 at 7 06 48 AM](https://github.com/defenseunicorns/defense-unicorns-hugo-theme/assets/8195127/c05824fd-9ac6-4400-9bb8-e6700a2f6255)
This is what I'm getting on the deployed, prod-built site.
