### ISSUE TITLE
Need to replace favicon with one that doesn't stretch - 32px

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/defense-unicorns-hugo-theme#95]
## Current

<img width="83" alt="Screenshot 2023-08-14 at 2 33 44 PM" src="https://github.com/defenseunicorns/defense-unicorns-hugo-theme/assets/92826525/c18d8e53-5b9c-4a8a-aa87-4d6a7b88702e">

## Update 

Update all PNG to new - non-squished Doug. 

Sizes available in Zip - 
<img width="327" alt="Screenshot 2023-08-14 at 2 53 53 PM" src="https://github.com/defenseunicorns/defense-unicorns-hugo-theme/assets/92826525/5221cc0c-d105-4c73-9bd8-185045715e3e">

## Files
[Hugo Docs.faviconszip.zip](https://github.com/defenseunicorns/defense-unicorns-hugo-theme/files/12345912/Hugo.Docs.faviconszip.zip)

**Comment by bdfinst** [comment]
Done
